# Generated by Django 2.2.3 on 2020-10-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summary_vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rezyumi',
            field=models.ImageField(blank=True, null=True, upload_to='resume/'),
        ),
    ]
