# Generated by Django 2.2.3 on 2020-10-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary_vacancy', '0002_student_rezyumi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='rezyumi',
        ),
    ]
