# Generated by Django 2.2.3 on 2020-10-21 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting_department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accounting_departments', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '5. Бухгалтерия, управленческий учет, финансы предприятия',
                'verbose_name_plural': '5. Бухгалтерия, управленческий учет, финансы предприятия',
            },
        ),
        migrations.CreateModel(
            name='Administrative_staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrative_staffs', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '2. Административный персонал',
                'verbose_name_plural': '2. Административный персонал',
            },
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arts', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '13. Искусство, развлечения, масс-медиа',
                'verbose_name_plural': '13. Искусство, развлечения, масс-медиа',
            },
        ),
        migrations.CreateModel(
            name='Banks_investments_leasing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banks_investments_leasings', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '3. Банки, инвестиции, лизинг',
                'verbose_name_plural': '3. Банки, инвестиции, лизинг',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildings', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '23. Строительство, недвижимость',
                'verbose_name_plural': '23. Строительство, недвижимость',
            },
        ),
        migrations.CreateModel(
            name='Car_business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_businesss', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '1. Автомобильный бизнес',
                'verbose_name_plural': '1. Автомобильный бизнес',
            },
        ),
        migrations.CreateModel(
            name='Consulting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultings', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '14. Консультирование',
                'verbose_name_plural': '14. Консультирование',
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controls', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '25. Управление персоналом, тренинги',
                'verbose_name_plural': '25. Управление персоналом, тренинги',
            },
        ),
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extractions', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '8. Государственная служба, некоммерческие организации',
                'verbose_name_plural': '8. Государственная служба, некоммерческие организации',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '9. Домашний персонал',
                'verbose_name_plural': '9. Домашний персонал',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informations', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '12. Информационные технологии, интернет, телеком',
                'verbose_name_plural': '12. Информационные технологии, интернет, телеком',
            },
        ),
        migrations.CreateModel(
            name='Installations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installationss', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '11. Инсталляция и сервис',
                'verbose_name_plural': '11. Инсталляция и сервис',
            },
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurances', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '22. Страхование',
                'verbose_name_plural': '22. Страхование',
            },
        ),
        migrations.CreateModel(
            name='Marketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketings', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '15. Маркетинг, реклама, PR',
                'verbose_name_plural': '15. Маркетинг, реклама, PR',
            },
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procurements', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '10. Закупки',
                'verbose_name_plural': '10. Закупки',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productions', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '20. Производство, сельское хозяйство',
                'verbose_name_plural': '20. Производство, сельское хозяйство',
            },
        ),
        migrations.CreateModel(
            name='Safety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safetys', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '4. Безопасность',
                'verbose_name_plural': '4. Безопасность',
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saless', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '19. Продажи',
                'verbose_name_plural': '19. Продажи',
            },
        ),
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportss', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '22. Спортивные клубы, фитнес, салоны красоты',
                'verbose_name_plural': '22. Спортивные клубы, фитнес, салоны красоты',
            },
        ),
        migrations.CreateModel(
            name='Start',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '18. Начало карьеры, студенты',
                'verbose_name_plural': '18. Начало карьеры, студенты',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('states', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '7. Государственная служба, некоммерческие организации',
                'verbose_name_plural': '7. Государственная служба, некоммерческие организации',
            },
        ),
        migrations.CreateModel(
            name='The_medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_medicine', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '16. Медицина, фармацевтика',
                'verbose_name_plural': '16. Медицина, фармацевтика',
            },
        ),
        migrations.CreateModel(
            name='The_science',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_sciences', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '17. Наука, образование',
                'verbose_name_plural': '17. Наука, образование',
            },
        ),
        migrations.CreateModel(
            name='Top_management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_managements', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '6. Высший менеджмент',
                'verbose_name_plural': '6. Высший менеджмент',
            },
        ),
        migrations.CreateModel(
            name='Tourism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tourisms', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '24. Туризм, гостиницы, рестораны',
                'verbose_name_plural': '24. Туризм, гостиницы, рестораны',
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transports', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '24. Транспорт, логистика',
                'verbose_name_plural': '24. Транспорт, логистика',
            },
        ),
        migrations.CreateModel(
            name='Working',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workings', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '21. Рабочий персонал',
                'verbose_name_plural': '21. Рабочий персонал',
            },
        ),
    ]
