# Generated by Django 2.2.3 on 2020-10-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lawyerss', models.CharField(max_length=100, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': '28. Юристы',
                'verbose_name_plural': '28. Юристы',
            },
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': '24. Строительство, недвижимость', 'verbose_name_plural': '24. Строительство, недвижимость'},
        ),
        migrations.AlterModelOptions(
            name='control',
            options={'verbose_name': '27. Управление персоналом, тренинги', 'verbose_name_plural': '27. Управление персоналом, тренинги'},
        ),
        migrations.AlterModelOptions(
            name='insurance',
            options={'verbose_name': '23. Страхование', 'verbose_name_plural': '23. Страхование'},
        ),
        migrations.AlterModelOptions(
            name='tourism',
            options={'verbose_name': '26. Туризм, гостиницы, рестораны', 'verbose_name_plural': '26. Туризм, гостиницы, рестораны'},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'verbose_name': '25. Транспорт, логистика', 'verbose_name_plural': '25. Транспорт, логистика'},
        ),
        migrations.RenameField(
            model_name='the_medicine',
            old_name='the_medicine',
            new_name='the_medicines',
        ),
        migrations.CreateModel(
            name='Manager_profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession1', models.ManyToManyField(to='profession.Car_business')),
                ('profession10', models.ManyToManyField(to='profession.Procurement')),
                ('profession11', models.ManyToManyField(to='profession.Installations')),
                ('profession12', models.ManyToManyField(to='profession.Information')),
                ('profession13', models.ManyToManyField(to='profession.Art')),
                ('profession14', models.ManyToManyField(to='profession.Consulting')),
                ('profession15', models.ManyToManyField(to='profession.Marketing')),
                ('profession16', models.ManyToManyField(to='profession.The_medicine')),
                ('profession17', models.ManyToManyField(to='profession.The_science')),
                ('profession18', models.ManyToManyField(to='profession.Start')),
                ('profession19', models.ManyToManyField(to='profession.Sales')),
                ('profession2', models.ManyToManyField(to='profession.Administrative_staff')),
                ('profession20', models.ManyToManyField(to='profession.Production')),
                ('profession21', models.ManyToManyField(to='profession.Working')),
                ('profession22', models.ManyToManyField(to='profession.Sports')),
                ('profession23', models.ManyToManyField(to='profession.Insurance')),
                ('profession24', models.ManyToManyField(to='profession.Building')),
                ('profession25', models.ManyToManyField(to='profession.Transport')),
                ('profession26', models.ManyToManyField(to='profession.Tourism')),
                ('profession27', models.ManyToManyField(to='profession.Control')),
                ('profession28', models.ManyToManyField(to='profession.Lawyers')),
                ('profession3', models.ManyToManyField(to='profession.Banks_investments_leasing')),
                ('profession4', models.ManyToManyField(to='profession.Safety')),
                ('profession5', models.ManyToManyField(to='profession.Accounting_department')),
                ('profession6', models.ManyToManyField(to='profession.Top_management')),
                ('profession7', models.ManyToManyField(to='profession.State')),
                ('profession8', models.ManyToManyField(to='profession.Extraction')),
                ('profession9', models.ManyToManyField(to='profession.Home')),
            ],
            options={
                'verbose_name': '29. менеджер профессия',
                'verbose_name_plural': '29. менеджер профессия',
            },
        ),
    ]
