# Generated by Django 2.2.3 on 2020-10-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0002_auto_20201021_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vozmojno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vozmojnos', models.CharField(max_length=100, verbose_name='Тип занятости')),
            ],
            options={
                'verbose_name': '30. Тип занятости',
                'verbose_name_plural': '30. Тип занятости',
            },
        ),
    ]
