# Generated by Django 2.2.3 on 2020-10-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0003_vozmojno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejimrabota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejimrab', models.CharField(max_length=100, verbose_name='Режим работы')),
            ],
            options={
                'verbose_name': '31. Тип занятости',
                'verbose_name_plural': '31. Тип занятости',
            },
        ),
    ]
