# Generated by Django 2.2.3 on 2020-10-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profession', '0004_rejimrabota'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rejimrabota',
            options={'verbose_name': '31. Режим работы', 'verbose_name_plural': '31. Режим работы'},
        ),
    ]
